services:
  - type: web
    name: truthlensai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir project/backend app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
